sudo: required
services:
  - docker
env:
  #global:
  #  REGISTRY_USER=$REGISTRY_USER
  #  REGISTRY_PASS=$REGISTRY_PASS
  #- secret: "<something long>"

script:
  - echo REGISTRY_USER = $REGISTRY_USER && echo REGISTRY_PASS = $REGISTRY_PASS
  - docker build -f mac_de_docker/Dockerfile .
  - docker ps 
  - docker ps -a  
  - docker images

after_script:
  #- docker images
  script: image_id="` docker images | awk 'FNR == 2 {print $3}'`" && echo $image_id

test:
  script: docker run -it $image_id echo 'docker test 123'

before_deploy:
  #- docker login -u="$REGISTRY_USER" -p="$REGISTRY_PASS"
  - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin
deploy:
  provider: script
  # commit and push 
  script: docker commit $image_id yennanliu/mac_de_docker:V2 && docker push yennanliu/mac_de_docker:V2
  on:
    branch: master


