sudo: required
services:
  - docker
env:
  #global:
  #  REGISTRY_USER=$REGISTRY_USER
  #  REGISTRY_PASS=$REGISTRY_PASS

script:
  - echo REGISTRY_USER = $REGISTRY_USER && echo REGISTRY_PASS = $REGISTRY_PASS
  - docker build -f mac_de_docker/Dockerfile .
  - docker ps 
  - docker ps -a  
  - docker images

after_script:
  #- docker images
  script: container_id="` docker ps | awk 'FNR == 2 {print $1}'`" && echo container_id = $container_id && image_id="` docker ps | awk 'FNR == 2 {print $2}'`" && echo image_id = $image_id 

test:
  script: docker run -it $container_id echo 'docker test 123'

before_deploy:
  #- docker login -u="$REGISTRY_USER" -p="$REGISTRY_PASS"
  - if echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin ; then echo "docker login OK!" else echo "docker login failed" fi 
deploy:
  provider: script
  # commit and push 
  script: docker commit $container_id yennanliu/mac_de_docker:V2 && docker push yennanliu/mac_de_docker:V2
  on:
    branch: master


