version: '2'
services:
  app:
    build: .
    ports:
    - "8080:8080"
    links:
    - db
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
